package ca.study.scenary.aedes;

import java.util.List;

import br.ufes.inf.lprm.scene.model.impl.Situation;
import br.ufes.inf.lprm.scene.util.SituationHelper;
import br.ufes.inf.lprm.situation.annotations.part;
import br.ufes.inf.lprm.situation.model.events.*;
import ca.study.scenary.entities.*;

declare AedesSituation extends Situation
	sc: Scenary @part
	houses: List @part
	mosquitos: List @part
end

declare LifeMosquito extends Situation
	life: Mosquito @part
end

declare ScenarySituation extends Situation
	sc: Scenary @part
	houses: List @part
	mosq: Mosquito @part
end

		
rule "Mosquito pode voar (event)"
@role(situation)
@type(ScenarySituation)
	when
		sc: Scenary(houses: scenary)
		house: House() from houses
		mosq: Mosquito(controlfly==false) from house.mosquitos
		
	then
		SituationHelper.situationDetected(drools);
end

rule "Vida mosquito"
@role(situation)
@type(LifeMosquito)
    when
        life: Mosquito(days <= 38, controlfly==false)
        
    then
        SituationHelper.situationDetected(drools);
end

rule "Dispara situação de ScenarySituation (test)"
	when
		$sit: ScenarySituation()
	then
		System.out.println("Situação de ScenarySituation disparada!");
end

rule "Mosquito pode voar (situation)"
	when
		$sit: LifeMosquito()
	then
		System.out.println("Mosquito pode voar");
end

rule "Verifica se a quantidade de mosquitos em uma casa é maior que 1"
@role(situation)
@type(AedesSituation)
	when
		sc: Scenary(houses: scenary)
		house: House() from houses
		mosquitos: List(size >= 1) from accumulate(
			mosquito: Mosquito(houseId == house.houseId, house.mosquitos.size > 0) over window:time(24h),
			collectList(mosquito)
		)
		
	then
		SituationHelper.situationDetected(drools);
end

rule "Tem mosquito na casa"
	when
		$sit: AedesSituation($m: mosquitos) 
	then
		System.out.println("Existe mosquito na casa " + $m.get(0));
end


declare liveMosquito extends Situation
	mosquito: Mosquito @part
end

declare MosquitoNotMoved extends Situation
	house: House @part
	mosquito: Mosquito @part
end

declare MosquitoNotLayed extends Situation
	house: House @part
	mosquito: Mosquito @part
end

rule "liveMosquito"
@role(situation)
@type(liveMosquito)
    when
    	    mosquito: Mosquito(days<38)
    then
        SituationHelper.situationDetected(drools);
end

rule "MosquitoNotMoved"
@role(situation)
@type(MosquitoNotMoved)
    when
     house: House()
    	    mosquito: Mosquito(controlfly==false) from house.getMosquitos()
        
    then
        SituationHelper.situationDetected(drools);
end

rule "MosquitoNotLayed"
@role(situation)
@type(MosquitoNotLayed)
    when
     	house: House()
        mosquito: Mosquito(controleggs==false) from house.getMosquitos()
    then
        SituationHelper.situationDetected(drools);
end

rule "moving"
	when
		$sit: liveMosquito($mosquito:mosquito)
		$sit2: MosquitoNotMoved(house:house,mosquito == $mosquito)
	then
		house.changeMosquito($mosquito);
		System.out.println("Mosquito has moved");
		update(house)
		update($mosquito)
end

rule "laying eggs"
when
		$sit: liveMosquito($mosquito:mosquito)
		$sit2: MosquitoNotLayed(house:house,mosquito == $mosquito)
	then
		$mosquito.setControleggs(true);
        house.addEggs();
		System.out.println("Mosquito has layed eggs");
		update(house)
		update($mosquito)
end

